// <auto-generated />
namespace TaskUIS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class fix1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix1));
        
        string IMigrationMetadata.Id
        {
            get { return "202505030138477_fix1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
